### ISSUE TITLE
Emoji support

### ISSUE THREAD

**Issue by Evonder** [geluk/matrix-webhook-gateway#15]
Is there any plan on integrating the ability to use emojis?

One use of webhooks for me is fail2ban notifications using ipinfo for showing flags (:us:).

**Comment by geluk** [comment]
Would you mind explaining your use case a bit further? I'm planning to improve emoji handling in the application in a few places, namely:
 - Automatically converting tags such as `:smile:` to a UTF-8 emoji: `😄`
 - Allowing webhooks to use emoji avatars (similar to how Slack does it, this should improve compatibility with applications that generate Slack webhooks)

Since the application supports UTF-8 text, sending emoji as UTF-8 sequences already works. That means that if you have control over what fail2ban sends, you can include the country flags there. If not, you can also create a [plugin](https://github.com/geluk/matrix-webhook-gateway#plugins) to replace country names/codes in the message with flags.

If you can share an example fail2ban notification, I can help you figure out how to make this work.

**Comment by Evonder** [comment]
I have modified my python script to use a library specifically to convert flag ASCII to Unicode and vise-versa. So in the long run I have addressed my issue.

I am having a few other issues that I will post in a separate ticket.

**Comment by geluk** [comment]
This is now implemented in version 1.1.
